### ISSUE TITLE
Wild bug appears!

### ISSUE THREAD

**Issue by jmann6** [lightning-power-users/node-launcher#273]
* **I'm submitting a ...**
  - [X ] bug report
  - [ ] feature request
  - [ ] support request

* **What is the current behavior?**
Wild bug appears! 
Please copy this text and open an issue on GitHub.
Node Launcher version 6.0.2

Error information:

'NoneType' object has no attribute 'split'
File "node_launcher\node_set\lnd.py", line 192, in config_file_changed

* **If the current behavior is a bug, please provide the steps to reproduce**
When updating to 6.0.2 the bug appeared.

* **What is the expected behavior?**

* **What is the motivation / use case for changing the behavior?**

* **Please tell us about your environment:**

  - Operating System: [ Windows 10 Home 64 bit ]

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

**Comment by GamerOfChains** [comment]
Same problem here.

**Comment by PierreRochard** [comment]
Hi @jmann6 and @GamerOfChains! Thank you for reporting this bug, try out the latest release and let me know if it has any issues (or if you have any feature requests!)

Fixed by https://github.com/lightning-power-users/node-launcher/commit/adf25fc0f81760e52d15c532452548b8f400895f

Cheers

**Comment by jmann6** [comment]
Hi Pierre,  I ran 6.0.4 and I get this error now.  Keep up the great work.  Cheers!
![wildbug](https://user-images.githubusercontent.com/3744618/56086265-57616880-5e10-11e9-9877-7fbad6870059.PNG)
